### ISSUE TITLE
Create a feed from an accounts followers

### ISSUE THREAD

**Issue by bmann** [ATProtoApps/community#1]
I have an account, [atprotocol.dev](https://bsky.app/profile/atprotocol.dev) that is following people with custom domain names.

I would like to turn this into a feed, which I _think_ can be done by turning it into a _list_

Would like a small script that when run, takes an account's followers, and creates / updates a list from it.

That list can then be used as input into Skyfeed or other feed creators.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/ATProtoApps) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/ATProtoApps/community/issues/1">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/ATProtoApps/community/issues/1/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/ATProtoApps/community/issues/1/pledge.svg">
</picture>
</a>

**Comment by futurGH** [comment]
This should work? Just need to fill in the variables above the ----- comment.

https://gist.github.com/futurGH/e57331e29cf9330d6c676ca75c597847

**Comment by futurGH** [comment]
Might've been a network error, updated the gist to handle that a bit better

**Comment by bmann** [comment]
@futurGH I checked it in here now into a scripts folder. I'm going to close this issues...which I _think_ will then issue the Polar funding. Thanks for the script and thanks for experimenting!

**Comment by bmann** [comment]
Thank you @futurGH for contributing to close this issue! ⭐

The rewards from this issue, totaling $25, has been shared with you.

**What now?**

1. Create a [Polar](https://polar.sh) account
2. See incoming rewards & setup Stripe to receive them
3. Get payouts as backers finalize their payments

_If you already have a Polar account setup, you don't need to do anything._

**Comment by bmann** [comment]
OK, I made this a 90% (for @futurGH) and 10% (this repo / me holding it in trust) split. @futurGH if creating a Stripe account is a pain, I can also I think update it to be 100% for AT Proto Devs and I can transfer funds out of band. Hit me on the Discord for more chatting :)

**Comment by futurGH** [comment]
Gotcha, I'll see how difficult the process is
